import type { Metadata } from "next"; // 페이지 메타데이터 타입 (SEO용)
import { Do_Hyeon, Geist_Mono, } from "next/font/google"; // Google Fonts를 Next.js 방식으로 불러오기
import "./globals.css"; // 전역 스타일 (reset, 공통 디자인 등)

// Do Hyeon (기본 본문용 폰트)
const doHyeon = Do_Hyeon({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
  variable: "--font-do-hyeon",
});

// Geist Mono (코드, 숫자 등 고정폭 텍스트용)
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// 🌐 페이지 전역 메타데이터 설정
export const metadata: Metadata = {
  title: "Round", // 브라우저 탭 제목
  description: "Generated by Readdy", // 검색엔진 및 SNS 미리보기용 설명
};

// 💡 RootLayout: 앱 전체의 기본 레이아웃 구조 정의
// 모든 페이지(app/page.tsx 등)는 children으로 여기에 렌더링됨
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" suppressHydrationWarning={true}>
      {/* body에 폰트 변수 클래스 적용 */}
      <body className={`${doHyeon.className} ${geistMono.variable} antialiased`}>
        {/* 각 페이지의 내용이 여기에 표시됨 */}
        {children}
      </body>
    </html>
  );
}
